version: '3.5'
services:
    aws:
        container_name: aws-cli
        image: tommynovember7/aws-cli:latest
        environment:
            - AWS_ACCESS_KEY_ID=$AWS_KEY
            - AWS_SECRET_ACCESS_KEY=$AWS_SECRET
            - AWS_DEFAULT_REGION=$AWS_REGION
        volumes:
            - ./:/var/project
        working_dir: /var/project
        entrypoint: ['/usr/local/bin/aws']