version: '3.7'
services:
  app:
    container_name: "app-node12"
    build:
      context: docker/node
      dockerfile: Dockerfile
    volumes:
      - ./:/var/project
    working_dir: /var/project

  hadolint:
    container_name: hadolint
    image: hadolint/hadolint:latest-debian
    volumes:
      - ./:/var/project
    working_dir: /var/project
    entrypoint: ['/bin/hadolint', '--config', './docker/hadolint.yaml']

  aws:
    container_name: aws-cli
    image: tommynovember7/aws-cli:latest
    environment:
      - AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY
      - AWS_DEFAULT_REGION=$AWS_DEFAULT_REGION
    volumes:
      - ./:/var/project
    working_dir: /var/project
    entrypoint: ['/usr/local/bin/aws']